import type { Metadata } from "next";
import { Providers } from "../providers";
import localFont from "next/font/local";
import Navbar from "@/components/navbar";

export const GothamFont = localFont({
  src: "../../assets/fonts/Gotham Pro Black.ttf",
});

export const metadata: Metadata = {
  title: "Res Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`min-h-screen w-screen flex items-center justify-center ${GothamFont.className}`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
