import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/components/navbar";
import AppProvider from "@/shared/context";

export const GothamFont = localFont({
  src: "../../assets/fonts/Gotham Pro Black.ttf",
});

export const metadata: Metadata = {
  title: "Res Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <main>
        <Navbar />
        {children}
      </main>
    </AppProvider>
  );
}
