import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Providers } from "./providers";
import AppProvider from "@/shared/context";

export const GothamFont = localFont({
  src: "../assets/fonts/Gotham Pro Black.ttf",
});

export const metadata: Metadata = {
  title: "Res Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`min-h-screen w-[480px] mx-auto border-x-1 ${GothamFont.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
