import type { Metadata } from "next";
import { Providers } from "./providers";
import localFont from "next/font/local";
import "./globals.css";

export const akiraFont = localFont({
  src: "../assets/fonts/Gotham Pro Black.ttf",
});

export const metadata: Metadata = {
  title: "Res Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`min-h-screen w-screen flex items-center justify-center ${akiraFont.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
